
server:
  port: 8001
  servlet:
    context-path: /service1
    session:
      cookie:
        name: oauth-service-1
        path: /

security:
  oauth2:
    client:
      clientId: client_1
      clientSecret: 123456
      # 获取访问令牌的URI
      accessTokenUri: http://localhost:8000/auth-server/oauth/token
      # 将用户重定向到的授权URI
      userAuthorizationUri: http://localhost:8000/auth-server/oauth/authorize
    resource:
      # 获取当前用户详细信息
      userInfoUri: http://localhost:8000/auth-server/security/getUserInfo

spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    host: localhost
    port: 6379
    # 连接密码（默认为空）
    password:
    # 连接超时时间（毫秒)
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

logging:
  level:
    com.shpun: debug
